package indexer

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Tier 1. No node, no npm, no registry: planInstall reads the tree and nothing
// else, which is the whole reason it is a separate function. Whether the command
// it picks actually installs anything is a tier 3 claim, asserted by
// TestAcceptance_SingleRepository_TypeScript (yarn) and _Angular (bun).

// Lockfiles, and the classic-yarn banner yarnFreezeFlag reads.
const (
	yarnClassicLock = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n"
	yarnBerryLock   = "# This file is generated by running \"yarn install\"\n\n__metadata:\n  version: 8\n"
)

// jsTree writes files with real content, which tree() cannot: yarn's freeze flag
// is chosen by reading the lockfile.
func jsTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(root, name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func TestPlanInstall_LockfileSelectsTheManager(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		want  string
	}{
		{"pnpm", map[string]string{"pnpm-lock.yaml": "lockfileVersion: '9.0'\n"}, "pnpm install --frozen-lockfile"},
		{"yarn classic", map[string]string{"yarn.lock": yarnClassicLock}, "yarn install --frozen-lockfile"},
		{"yarn berry", map[string]string{"yarn.lock": yarnBerryLock}, "yarn install --immutable"},
		{"bun", map[string]string{"bun.lock": "{}\n"}, "bun install --frozen-lockfile"},
		{"bun pre-1.2", map[string]string{"bun.lockb": "\x00binary"}, "bun install --frozen-lockfile"},
		{"npm", map[string]string{"package-lock.json": "{}"}, "npm ci --silent --no-audit --no-fund"},
		{"npm shrinkwrap", map[string]string{"npm-shrinkwrap.json": "{}"}, "npm ci --silent --no-audit --no-fund"},
		{"no lockfile", map[string]string{"package.json": "{}"}, "npm install --silent --no-audit --no-fund"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := planInstall(jsTree(t, tc.files)).String(); got != tc.want {
				t.Errorf("planInstall = %q, want %q", got, tc.want)
			}
		})
	}
}

// A repository carrying two lockfiles is ambiguous, and the ambiguity is real:
// one `npm install` in a yarn tree leaves a package-lock.json behind for good.
// The order is a decision, so it is pinned rather than left to switch-statement
// drift.
func TestPlanInstall_NpmsLockfileLosesToEveryOther(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		want  string
	}{
		{"pnpm over everything", map[string]string{
			"pnpm-lock.yaml": "", "yarn.lock": yarnClassicLock, "bun.lock": "{}", "package-lock.json": "{}",
		}, "pnpm"},
		{"yarn over npm", map[string]string{"yarn.lock": yarnClassicLock, "package-lock.json": "{}"}, "yarn"},
		{"bun over npm", map[string]string{"bun.lock": "{}", "package-lock.json": "{}"}, "bun"},
		{"bun.lock over bun.lockb", map[string]string{"bun.lock": "{}", "bun.lockb": "\x00"}, "bun"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := planInstall(jsTree(t, tc.files)).manager; got != tc.want {
				t.Errorf("manager = %q, want %q", got, tc.want)
			}
		})
	}
}

// "No build file is ever modified" covers lockfiles, so every install is frozen
// and only npm -- which refuses a drifted lockfile outright -- carries a fallback
// that may rewrite one.
func TestPlanInstall_OnlyNpmMayRewriteALockfile(t *testing.T) {
	frozen := map[string]string{
		"pnpm-lock.yaml": "--frozen-lockfile",
		"yarn.lock":      "--frozen-lockfile", // classic; berry is covered above
		"bun.lock":       "--frozen-lockfile",
	}
	for lock, flag := range frozen {
		content := "{}"
		if lock == "yarn.lock" {
			content = yarnClassicLock
		}
		plan := planInstall(jsTree(t, map[string]string{lock: content}))
		if !slicesContain(plan.args, flag) {
			t.Errorf("%s: plan is %q, want it to carry %s", lock, plan, flag)
		}
		if plan.fallback != nil {
			t.Errorf("%s: plan has fallback %v; only npm may fall back to an unfrozen install", lock, plan.fallback)
		}
	}

	npm := planInstall(jsTree(t, map[string]string{"package-lock.json": "{}"}))
	if npm.fallback == nil {
		t.Fatal("npm plan has no fallback; a lockfile drifted from package.json would stop indexing entirely")
	}
	if !slicesContain(npm.fallback, "install") {
		t.Errorf("npm fallback = %v, want it to run `npm install`", npm.fallback)
	}
}

// With no lockfile there is nothing to freeze, and --frozen-lockfile would fail
// on a tree that installs perfectly well.
func TestPlanInstall_NoLockfileHasNothingToFreeze(t *testing.T) {
	plan := planInstall(jsTree(t, map[string]string{"package.json": "{}"}))
	if plan.lockfile != "" {
		t.Errorf("lockfile = %q, want it empty", plan.lockfile)
	}
	for _, a := range plan.args {
		if strings.Contains(a, "frozen") || a == "--immutable" || a == "ci" {
			t.Errorf("plan is %q, want a plain install", plan)
		}
	}
}

// The failure mode this whole change exists to remove: reaching for npm because
// the project's own manager is missing. It installs a dependency tree the project
// has never used, and an index built against the wrong tree is wrong in ways
// nothing downstream can detect.
func TestInstallDependencies_MissingManagerIsFatalRatherThanNpm(t *testing.T) {
	dir := jsTree(t, map[string]string{"package.json": "{}", "pnpm-lock.yaml": ""})
	t.Setenv("PATH", t.TempDir()) // an empty directory: nothing is on $PATH

	r, err := newRunner(dir, nil)
	if err != nil {
		t.Fatal(err)
	}
	err = installDependencies(context.Background(), r, Unit{Prefix: "web", Dir: dir, Kind: KindTypeScript})
	if err == nil {
		t.Fatal("installDependencies succeeded with no package manager on $PATH")
	}
	for _, want := range []string{"pnpm", "pnpm-lock.yaml"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error = %q, want it to name %s", err, want)
		}
	}
}
